workflows:
  android-workflow:
    name: BLE Test Peripheral Android Workflow
    environment:
      java: 11
      gradle: "-Dorg.gradle.daemon=false"
    scripts:
      - name: Install dependencies
        script: |
          chmod +x gradlew
          ./gradlew dependencies
      - name: Build APK
        script: |
         ./gradlew assembleDebug
    artifacts:
      app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        - "kavinithees2696@gmail.com"






