workflows:
  android-workflow:
    name: BLE Test Peripheral Android Workflow
    environment:
      java: 11
    scripts:
      - name: Install dependencies
        script: gradle clean build
      - name: Build APK
        script: |
         ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk # Android artifact
    publishing:
      email:    
        recipients:
          - "kavinithees2696@gmail.com"
